# Generated by Django 5.0.7 on 2024-07-27 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('enrollment', models.DateTimeField(auto_now=True)),
                ('account', models.IntegerField()),
                ('bank', models.CharField(max_length=200)),
            ],
        ),
    ]
